municipality: Obec Ochodnica
address: Ochodnica 121, 023 35 Ochodnica
email: obec@ochodnica.sk
phone: 041 / 423 31 21
mobile: 0902 748 575
ico: '00314153'
mayor: Radoslav Ďuroška
mayor_phone: 0907 886 944
